# Generated by Django 3.1.2 on 2020-10-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('wins', models.IntegerField(blank=True, max_length=100)),
                ('losses', models.IntegerField(blank=True, max_length=100)),
            ],
        ),
    ]
