# Generated by Django 3.1.2 on 2020-10-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0002_auto_20201024_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_number', models.AutoField(primary_key=True, serialize=False)),
                ('home_team_score', models.IntegerField(default=0)),
                ('away_team_score', models.IntegerField(default=0)),
                ('home_team', models.CharField(max_length=50, null=True)),
                ('away_team', models.CharField(max_length=50, null=True)),
                ('winner', models.CharField(max_length=50, null=True)),
                ('loser', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
