# Generated by Django 3.1.2 on 2020-10-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0004_auto_20201024_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='week_number',
            field=models.IntegerField(default=1),
        ),
    ]
